name: github-action-reviewer-labels
url: https://github.com/franz-see/github-action-reviewer-labels
description: Automatically adds/removes labels on a pull request based on who the reviewers are. This is to allow people looking at the list of pull requests who is reviewing what.

default_events:
  - pull_request

default_permissions:
  checks: write
  metadata: read
  pull_requests: read
  single_file: read

