name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver version to tag the target with (e.g. 1.2.3)
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20.11.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: |
          tag='v${{ inputs.version }}'
          major_tag="${tag:0:2}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Release ${tag}"
          # Push the specific version tag and update the major version tag
          # Start with specific version tag which will error if it's taken
          git tag "$tag"
          git push origin "$tag"
          git tag -f "$major_tag"
          git push -f origin "$major_tag"
